### ISSUE TITLE
Feature request: a command option

### ISSUE THREAD

**Issue by azmeuk** [dominikwalk/importtime-output-wrapper#14] opened 2022-01-10 14:36 UTC
Hi. Thank you for this wonderful utility!
The one thing  importtime-output-wrapper is lacking is a `-c` option like python have. This would allow users to use something like `importtime_output_wrapper --format waterfall -c "import web; web.create_app()"`

What do you think?

**Comment by dominikwalk** [comment] 2022-01-10 15:45
Hi, I like your idea. 
Originally the tool was designed to check the import time for a single module, as that was my use case at the time. I find it good that it seems to have helped other people in the development, but i think for a wider application a `-c` option would be very useful.

Adding this feature should work relatively easily, since the actual `-X importtime` call is capsuled in a single subprocess...
https://github.com/dominikwalk/importtime-output-wrapper/blob/d6e1c87c597655370e6662bbb9cba8b758b9f0d7/importtime_output_wrapper.py#L37-L43
...which can easily be adapted to excecute a full python command if the `-c` option is used.

I would like to implement this feature in short and merge it into the tool, if you don't mind :)

**Comment by azmeuk** [comment] 2022-01-10 16:08
> I would like to implement this feature in short and merge it into the tool, if you don't mind :)
(Unless you have already implemented it or would like to do so, then you can of course create a pull request.)

Great to hear! Please do it :)

**Comment by dominikwalk** [comment] 2022-01-12 19:33
Implemented the feature and merged it into main branch. I will alse release a new package version for pypi. ✨

**Closed by dominikwalk** 2022-01-12 19:33 UTC
Labels: enhancement
